# Generated by Django 5.1.1 on 2024-09-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answser',
            new_name='answer',
        ),
    ]
