# Generated by Django 5.1.1 on 2024-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_answers_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
